### ISSUE TITLE
other Python packages for decision diagrams

### ISSUE THREAD

**Issue by johnyf** [thiagopbueno/pydd#1]
There are a couple of [Python BDD packages](https://github.com/johnyf/tool_lists/blob/master/bdd.md#python), in case they may be useful.

**Comment by thiagopbueno** [comment]
Thanks very much @johnyf. Currently I need a highly flexible and easy to use ADD (Algebraic DDs) implementation for my research projects.  As I couldn't find any library that satisfies these requirements (which rules out C/C++ bindings like pyCUDD), I am developing pyddlib totally in Python 3  as a code base for some experiments. If possible, I would pretty much appreciate if you could list my implementation in your [tool_lists](https://github.com/johnyf/tool_lists/blob/master/bdd.md#python).

**Comment by johnyf** [comment]
Thanks for the information.
